### PR TITLE
Add support for symfony serializer component v4

### PR DESCRIPTION
**Pull request by Vesquen**
* Fixed typo ELASTICSEARCH_HOST in .travis.yml
* Used Java9 as Java8 broke the travis build
* Added symfony serializer component v4

#SymfonyConHackday2017

### CODE REVIEW

**Comment by saimaz** [comment]
This is something for v6 version. Thank you for the PR. Let me double check everything, and this might be a good start for the Elasticsearch v6 support.

**Comment by reyostallenberg** [comment]
Why isn't this BC major upgrade of the serializer also a candidate to do in patch releases of all versions?

**Comment by saimaz** [comment]
I added serializer upgrade and Travis fixes in 6.0 beta version. Eventually will fix 5.0 branch as well.

**Comment by saimaz** [comment]
I added all those changes to the 5 branch base which will move to upper versions as well.

**Pull request closed without merging**
