### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by talentrydev**
Adds PHP 8.0 support, but bumps minimum PHP version to 7.2, because PHPUnit 8 requires at least PHP 7.2.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM :+1: 

Will for now fork and add `symfony/serializer:^5` support too

**Comment by Radiergummi** [comment]
@Ocramius you don't plan on supporting your fork longer-term, do you? :/

**Comment by Ocramius** [comment]
No, it will be removed once upstream gets a release

**Comment by marufmax** [comment]
its more than a year now

**Pull request closed without merging**
