### PR TITLE
ES 5 support: Changed syntax of script_score (fix for #175)

### PR DESCRIPTION
**Pull request by KnysakPatryk**

### CODE REVIEW

**Comment by KnysakPatryk** [comment]
What's up @saimaz? Is the code wrong or something? I can work on it if you just let me know ;)

**Comment by KnysakPatryk** [comment]
Today I checked dev-master branch on my project with complex ES queries and... it's working, but it's mandatory to merge this change. If something is wrong with this code, let me know. I can work on better implementation.

**Comment by saimaz** [comment]
Sorry for the delay @KnysakPatryk. I believe everything is fine with the code. Could you please rebase a PR to 5.x branch?

**Comment by KnysakPatryk** [comment]
I think I cannot do that (I don't have sufficient permissions to create new branch on your repository). If I'm wrong, correct me. Thanks

**Pull request merged**
