### PR TITLE
Allow 9.99 version from paragonie random compat

### PR DESCRIPTION
**Pull request by alexander-schranz**
inspired by: https://github.com/symfony/polyfill-php70/blob/1e24b0c4a56d55aaf368763a06c6d1c7d3194934/composer.json#L20

### CODE REVIEW

**Comment by michakpl** [comment]
Is there a chance to merge it soon? I need this change to install this package in my project

**Comment by saimaz** [comment]
Sure, I changed to a `*` in https://github.com/ongr-io/ElasticsearchDSL/commit/14b8fc60736711655fb6eea2e52964571dc6762a commit. It will allow all versions.

**Comment by michakpl** [comment]
@saimaz thank you

I didn't noticed that it was commit to 5.x, could you release also 6.x with this change?

**Comment by saimaz** [comment]
It's already there, will release a new patch for v6 after tests in travis will pass.

**Pull request closed without merging**
