### PR TITLE
Feature/add custom parameter as methods

### PR DESCRIPTION
**Pull request by edwinsiebel**
As of [documentation](https://github.com/ongr-io/ElasticsearchDSL/blob/master/docs/HowTo/CustomParameters.md), the following methods were missing, and caused fatal errors.

* Add setTerminateAfter method
* Add setTimeout method

### CODE REVIEW

**Comment by saimaz** [comment]
Thanks for contribution @edwinsiebel !

It appears that you probably try to open a pull request from some strange source. Could you please fix merge conflicts and open a pull request to the 6.2 branch?

**Review by saimaz — CHANGES_REQUESTED** [review]
Please open a PR to 6.2 branch and solve the incompatibility issues.

**Comment by edwinsiebel** [comment]
I've made a branch from your master branch to my local account. Nothing word about that, I presume.

Would you like me to redo the commits but then on the 6.x branch or the the 7.x branch (which I didn't even see before)?

**Comment by saimaz** [comment]
Could you please rebase and check if tests pass?

**Comment by edwinsiebel** [comment]
It looks like the tests fail, but not on my code.

**Comment by saimaz** [comment]
The right way to rebase is to start your local repository from a 6.1, cherry-pick the commit and then push by force to the remote. There should be only 1 your commit without the history with my commits :)

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request


OR 

create another PR to the 6.1 and not the master branch.

**Comment by edwinsiebel** [comment]
Should be closed, and new PR is created: https://github.com/ongr-io/ElasticsearchDSL/pull/310

**Pull request closed without merging**
