### PR TITLE
fixes #237 - added support for date range keys

### LINKED ISSUE #237: DateRangeAggregation does not support 'key'
The RangeAggregation looks for the 'key' index in the `$ranges = []` passed to RangeAggregation, but DateRangeAggregation does not appear to do the same thing.

RangeAggregation also supports an optional `$keyed = false` parameter, which is missing from DateRangeAggregation preventing you from having keyed date ranges.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html

Copying over the logic for 'key' from RangeAggregation to DateRangeAggregation appears to solve the problem.

### PR DESCRIPTION
**Pull request by zoul0813**

### CODE REVIEW

**Comment by zoul0813** [comment]
Looks like the Travis build script isn't working properly - it appears to have failed trying to install some packages on the build server?

**Comment by saimaz** [comment]
The PR should be open to 5.0 branch. If you would rebase it, Travis testing would work as well.

**Comment by zoul0813** [comment]
@saimaz hopefully that does the trick? thanks.

**Comment by saimaz** [comment]
Not really, you just merged branch instead of rebasing. I created a right PR with cherry-picked commit from your PR. https://github.com/ongr-io/ElasticsearchDSL/pull/252

**Pull request closed without merging**
