### PR TITLE
fields was changed to stored_fields in elasticsearch 5.0 #169

### PR DESCRIPTION
**Pull request by KnysakPatryk**
Hello

I applied the fix for renamed parameter in ES 5.0.

Thanks for this great library!

### CODE REVIEW

**Comment by saimaz** [comment]
This change introduces a BC break. I would rather include `stored_fields` as a new field and mark `fields` as deprecated. Then in the next major version, we can remove `fields` along with supporting from Elasticsearch `5.0`. Until then, both versions could have support, just by using fields you need.

**Comment by KnysakPatryk** [comment]
Sure, we can handle it like that, but if you test this library with different version of ES, you will see that this library have huge problems with compability. I have tried it with ES 1/2/5 and it's a mess.

**Comment by saimaz** [comment]
The `2.x` should support `2.x` and `5.x`. There is no doubt to drop a support for Elasticsearch `2.x`. But by introducing changes we need to mark deprecations. 

If you notice any other issues besides `stored_fields` and `script_score` please let me know. I will include functional tests for it to make sure it will work well with `5.0`.

**Comment by saimaz** [comment]
Related to #177

**Pull request closed without merging**
