### PR TITLE
PSR-4 Autoloading - Rename file

### LINKED ISSUE #319: MatrixStatsAggregation.php does not comply with psr-4 autoloading standard
When installing this library with Composer the following warning is shown:
```
Deprecation Notice: Class ONGR\ElasticsearchDSL\Aggregation\Matrix\MaxAggregation located in ./vendor/ongr/elasticsearch-dsl/src/Aggregation/Matrix/MatrixStatsAggregation.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

### PR DESCRIPTION
**Pull request by chrysanthos**
I renamed MatrixStatsAggregation.php to MaxAggregation.php to comply with PSR-4 autoloading standard. 

The next [major version of Composer (v2)](https://github.com/composer/composer/milestone/23) will not autoload such files so this has to eventually happen I suppose. 

I am not sure if this is a breaking change but I don't see why it would be since the classname and namespace remained as is. 

Closes #319

### CODE REVIEW

**Review by wawan93 — APPROVED** [review]
Please, merge this

**Comment by wawan93** [comment]
Closes #319

**Comment by danineto** [comment]
Hello,

We still have this issue :(

**Comment by alexleeelkins** [comment]
please merge this

**Comment by mitelg** [comment]
composer 2 RC2 was just released and according to the developers, it will soon released as stable. so this should really be fixed soon :blush:

**Comment by 84m** [comment]
i just merged this commit in the [7.2 branch](https://github.com/ongr-io/ElasticsearchDSL/tree/7.2) with 8c75b81

**Comment by mitelg** [comment]
would it be possible, to merge this also into the 7.1 branch? we are depending on Symfony 4.4 (LTS) and therefore we cannot use the current 7.2.1 version, where this was fixed

**Comment by mitelg** [comment]
created a PR :blush: https://github.com/ongr-io/ElasticsearchDSL/pull/338

**Pull request closed without merging**
